name: temtem

networks:
  koer-network:
    external: true

services:
  migrate:
    image: migrate/migrate:v4.18.1
    profiles: ["tools"]
    networks:
      - koer-network
    volumes:
      - ../migrations:/migrations:ro
    command:
      - -path=/migrations
      - -database=postgres://temtem:temtem@postgres:5432/temtem?sslmode=disable
      - up

  app:
    profiles: ["app"]
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    networks:
      - koer-network
    environment:
      TEMTEM_POSTGRES__HOST: postgres
      TEMTEM_REDIS__ADDR: redis:6379
    ports:
      - "9090:9090"
      - "8080:8080"
      - "9100:9100"
